[package]
name = "cses_rs"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name="weird_algorithm"
path="src/weird_algorithm.rs"
[[bin]]
name="missing_number"
path="src/missing_number.rs"
[[bin]]
name="repetitions"
path="src/repetitions.rs"
[[bin]]
name="increasing_array"
path="src/increasing_array.rs"
[[bin]]
name="permutations"
path="src/permutations.rs"
[[bin]]
name="number_spiral"
path="src/number_spiral.rs"
[[bin]]
name="two_knights"
path="src/two_knights.rs"
[[bin]]
name="two_sets"
path="src/two_sets.rs"
[[bin]]
name="trailing_zeros"
path="src/trailing_zeros.rs"
[[bin]]
name="coin_piles"
path="src/coin_piles.rs"
[[bin]]
name="palindrome_reorder"
path="src/palindrome_reorder.rs"
[[bin]]
name="gray_code"
path="src/gray_code.rs"
