[package]
name = "comprog_rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name="delsort"
path="src/delsort.rs"
[[bin]]
name="sleepsort"
path="src/sleepsort.rs"
[[bin]]
name="67_integer"
path="src/67_integer.rs"
[[bin]]
name="67_67_integer"
path="src/67_67_integer.rs"
[[bin]]
name="67_permutation"
path="src/67_permutation.rs"
[[bin]]
name="67_oeis"
path="src/67_oeis.rs"
[[bin]]
name="flipping_binary_string"
path="src/flipping_binary_string.rs"
[[bin]]
name="registration_system"
path="src/registration_system.rs"
[[bin]]
name="spreadsheets"
path="src/spreadsheets.rs"
[[bin]]
name="67_xor"
path="src/67_xor.rs"
[[bin]]
name="67_tree"
path="src/67_tree.rs"
[[bin]]
name="67_counting"
path="src/67_counting.rs"
[[bin]]
name="simple_gcd_easy"
path="src/simple_gcd_easy.rs"
[[bin]]
name="triple_operations"
path="src/triple_operations.rs"
[[bin]]
name="game_with_a_fraction"
path="src/game_with_a_fraction.rs"
[[bin]]
name="kitchen_utensils"
path="src/kitchen_utensils.rs"
[[bin]]
name="cinema_cashier"
path="src/cinema_cashier.rs"
[[bin]]
name="portal"
path="src/portal.rs"
[[bin]]
name="annoying_game"
path="src/annoying_game.rs"
[[bin]]
name="thu"
path="src/thu.rs"
[[bin]]
name="grid_covering"
path="src/grid_covering.rs"
[[bin]]
name="time_display_stickers"
path="src/time_display_stickers.rs"
[[bin]]
name="bench"
path="src/bench.rs"
[[bin]]
name="divisive_battle"
path="src/divisive_battle.rs"
[[bin]]
name="lost_soul"
path="src/lost_soul.rs"
[[bin]]
name="retaliation"
path="src/retaliation.rs"
[[bin]]
name="adrenaline_rush"
path="src/adrenaline_rush.rs"
[[bin]]
name="fun_game"
path="src/fun_game.rs"
[[bin]]
name="parity_and_sum"
path="src/parity_and_sum.rs"
[[bin]]
name="light_switches"
path="src/light_switches.rs"
[[bin]]
name="nastya_and_door"
path="src/nastya_and_door.rs"
[[bin]]
name="marisa_steals_reimus_takeout"
path="src/marisa_steals_reimus_takeout.rs"
[[bin]]
name="remilia_plays_sudoku"
path="src/remilia_plays_sudoku.rs"
[[bin]]
name="cirno_and_number"
path="src/cirno_and_number.rs"
[[bin]]
name="wonderful_contest"
path="src/wonderful_contest.rs"
[[bin]]
name="artistic_balance_tree"
path="src/artistic_balance_tree.rs"
[[bin]]
name="median_partition"
path="src/median_partition.rs"
[[bin]]
name="digit_string"
path="src/digit_string.rs"
[[bin]]
name="arrange_the_numbers_in_a_circle"
path="src/arrange_the_numbers_in_a_circle.rs"
[[bin]]
name="gcd_unlucky"
path="src/gcd_unlucky.rs"
[[bin]]
name="good_schedule"
path="src/good_schedule.rs"
[[bin]]
name="we_be_flipping"
path="src/we_be_flipping.rs"
[[bin]]
name="zilhy_and_mex_and_max"
path="src/zilhy_and_mex_and_max.rs"
[[bin]]
name="it_all_went_sideways"
path="src/it_all_went_sideways.rs"
[[bin]]
name="convergence"
path="src/convergence.rs"
[[bin]]
name="cake_leveling"
path="src/cake_leveling.rs"
[[bin]]
name="seating_arrangement"
path="src/seating_arrangement.rs"
[[bin]]
name="equal_multisets"
path="src/equal_multisets.rs"
[[bin]]
name="chipmunk_theo_and_equality"
path="src/chipmunk_theo_and_equality.rs"
[[bin]]
name="stamina_and_tasks"
path="src/stamina_and_tasks.rs"
[[bin]]
name="absolute_cinema"
path="src/absolute_cinema.rs"
[[bin]]
name="new_game"
path="src/new_game.rs"
[[bin]]
name="corner_twist"
path="src/corner_twist.rs"
[[bin]]
name="array_game"
path="src/array_game.rs"
[[bin]]
name="divisible_pairs"
path="src/divisible_pairs.rs"
[[bin]]
name="find_the_different_ones"
path="src/find_the_different_ones.rs"
[[bin]]
name="romantic_glasses"
path="src/romantic_glasses.rs"
[[bin]]
name="divide_and_equalize"
path="src/divide_and_equalize.rs"
[[bin]]
name="make_it_alternating"
path="src/make_it_alternating.rs"
[[bin]]
name="rigged"
path="src/rigged.rs"
[[bin]]
name="chips_on_the_board"
path="src/chips_on_the_board.rs"
[[bin]]
name="euclid_sequence_and_two_numbers"
path="src/euclid_sequence_and_two_numbers.rs"
[[bin]]
name="palindrome_twelve_and_two_terms"
path="src/palindrome_twelve_and_two_terms.rs"
[[bin]]
name="vessels_heights_and_two_versions"
path="src/vessels_heights_and_two_versions.rs"
[[bin]]
name="xor_expression_and_two_binary_numbers"
path="src/xor_expression_and_two_binary_numbers.rs"
