[package]
name = "comprog_rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name="delsort"
path="src/delsort.rs"
[[bin]]
name="sleepsort"
path="src/sleepsort.rs"
[[bin]]
name="67_integer"
path="src/67_integer.rs"
[[bin]]
name="67_67_integer"
path="src/67_67_integer.rs"
[[bin]]
name="67_permutation"
path="src/67_permutation.rs"
[[bin]]
name="67_oeis"
path="src/67_oeis.rs"
[[bin]]
name="flipping_binary_string"
path="src/flipping_binary_string.rs"
[[bin]]
name="registration_system"
path="src/registration_system.rs"
[[bin]]
name="spreadsheets"
path="src/spreadsheets.rs"
[[bin]]
name="67_xor"
path="src/67_xor.rs"
[[bin]]
name="67_tree"
path="src/67_tree.rs"
[[bin]]
name="67_counting"
path="src/67_counting.rs"
[[bin]]
name="simple_gcd_easy"
path="src/simple_gcd_easy.rs"
[[bin]]
name="triple_operations"
path="src/triple_operations.rs"
[[bin]]
name="game_with_a_fraction"
path="src/game_with_a_fraction.rs"
[[bin]]
name="kitchen_utensils"
path="src/kitchen_utensils.rs"
[[bin]]
name="cinema_cashier"
path="src/cinema_cashier.rs"
[[bin]]
name="portal"
path="src/portal.rs"
[[bin]]
name="annoying_game"
path="src/annoying_game.rs"
[[bin]]
name="thu"
path="src/thu.rs"
[[bin]]
name="grid_covering"
path="src/grid_covering.rs"
[[bin]]
name="time_display_stickers"
path="src/time_display_stickers.rs"
[[bin]]
name="bench"
path="src/bench.rs"
[[bin]]
name="divisive_battle"
path="src/divisive_battle.rs"
[[bin]]
name="lost_soul"
path="src/lost_soul.rs"
[[bin]]
name="retaliation"
path="src/retaliation.rs"
[[bin]]
name="adrenaline_rush"
path="src/adrenaline_rush.rs"
[[bin]]
name="fun_game"
path="src/fun_game.rs"
[[bin]]
name="parity_and_sum"
path="src/parity_and_sum.rs"
[[bin]]
name="light_switches"
path="src/light_switches.rs"
[[bin]]
name="nastya_and_door"
path="src/nastya_and_door.rs"
